CREATE TABLE swtor.RatingStats (
    Rating INT NOT NULL,
    LightPri INT NOT NULL,
    LightSec INT NOT NULL,
    MediumPri INT NOT NULL,
    MediumSec INT NOT NULL,
    HeavyPri INT NOT NULL,
    HeavySec INT NOT NULL,
    DmgMinSaber INT NOT NULL,
    DmgMaxSaber INT NOT NULL,
    DmgMinPistol INT NOT NULL,
    DmgMaxPistol INT NOT NULL,
    DmgMinStaff INT NOT NULL,
    DmgMaxStaff INT NOT NULL,
    DmgMinSniper INT NOT NULL,
    DmgMaxSniper INT NOT NULL,
    DmgMinCannon INT NOT NULL,
    DmgMaxCannon INT NOT NULL,
    DmgMinShotgun INT NOT NULL,
    DmgMaxShotgun INT NOT NULL,
    DmgMinKnife INT NOT NULL,
    DmgMaxKnife INT NOT NULL,
    FTPower INT NOT NULL,
    FOREIGN KEY (Rating) REFERENCES swtor.Items(Rating),
    PRIMARY KEY (Rating)
)